#!/usr/bin/env python3
"""
parse_ost_logs.py

Parses ost_space_and_usage.log generated by run_workloads.py and produces
a heatmap of bytes written per OST per workload profile (aggregated across
all runs, combined HDD + SSD).

The heatmap shows:
  - Y axis: profile_with_size_variant (e.g. small_contiguous_write_heavy_freq_1gb [HDD])
  - X axis: OST target ID (e.g. OST201, OST202 ...)
  - Color:  mean GiB written to that OST across all runs of that profile
            (calculated as BEFORE_free - AFTER_free per OST per run)

Usage:
    python3 parse_ost_logs.py
    python3 parse_ost_logs.py --log path/to/ost_space_and_usage.log
    python3 parse_ost_logs.py --log scripts/ost_space_and_usage.log --output output/ost_heatmap.png
    python3 parse_ost_logs.py --active-only   # skip OSTs with 0 bytes written across all profiles






    # Default paths (log in scripts/, output in output/)
python3 scripts/parse_ost_logs.py

# Explicit paths
python3 scripts/parse_ost_logs.py --log scripts/ost_space_and_usage.log --output output/ost_heatmap.png

# Skip OSTs that show 0 writes across all profiles (cleaner plot)
python3 scripts/parse_ost_logs.py --active-only

# Include offline nodes (colva1/colva4) — normally not useful
python3 scripts/parse_ost_logs.py --all-nodes
"""

import argparse
import os
import re
import sys
from collections import defaultdict

import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import seaborn as sns

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

DEFAULT_LOG    = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                              "ost_space_and_usage.log")
DEFAULT_OUTPUT = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                              "output", "ost_heatmap.png")

# Only show storage OSTs (node 2 and 3 in your setup) — skip offline nodes
# Set to None to include all OSTs found in the log
ACTIVE_NODE_IDS = {2, 3}

# ---------------------------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------------------------

def parse_args():
    parser = argparse.ArgumentParser(
        description="Parse ost_space_and_usage.log and generate OST heatmap."
    )
    parser.add_argument(
        "--log",
        default=DEFAULT_LOG,
        help=f"Path to ost_space_and_usage.log (default: {DEFAULT_LOG})"
    )
    parser.add_argument(
        "--output",
        default=DEFAULT_OUTPUT,
        help=f"Output PNG path (default: {DEFAULT_OUTPUT})"
    )
    parser.add_argument(
        "--active-only",
        action="store_true",
        help="Skip OSTs that have 0 bytes written across all profiles"
    )
    parser.add_argument(
        "--all-nodes",
        action="store_true",
        help="Include all nodes (including offline colva1/colva4). By default only nodes 2 and 3 are shown."
    )
    return parser.parse_args()


# ---------------------------------------------------------------------------
# Log parsing
# ---------------------------------------------------------------------------

# Matches:  ### OST SPACE (STORAGE) BEFORE profile_name [HDD] run1
# Also handles old format without (STORAGE):  ### OST SPACE BEFORE ...
SECTION_RE = re.compile(
    r"^### OST SPACE(?:\s+\(STORAGE\))?\s+(BEFORE|AFTER)\s+(.+?)\s+\[(HDD|SSD)\]\s+run(\d+)",
    re.IGNORECASE
)

# Matches a data row:   201    1862.1GiB     794.5GiB  43%  ...  2
DATA_ROW_RE = re.compile(
    r"^\s*(\d+)\s+([\d.]+)GiB\s+([\d.]+)GiB\s+\d+%\s+[\d.]+M\s+[\d.]+M\s+\d+%\s+(\d+)"
)


def parse_log(log_path, active_node_ids):
    """
    Parse the OST log file.

    Returns a dict:
        records[(profile, storage_type, run_index, timing)] = {ost_id: free_gib}

    timing is "BEFORE" or "AFTER".
    """
    if not os.path.isfile(log_path):
        print(f"ERROR: Log file not found: {log_path}")
        sys.exit(1)

    records = {}          # (profile, storage, run, timing) -> {ost_id: free_gib}
    current_key = None
    current_data = {}

    with open(log_path) as f:
        for line in f:
            line = line.rstrip()

            # Detect section header
            m = SECTION_RE.match(line)
            if m:
                # Save previous section if any
                if current_key and current_data:
                    records[current_key] = current_data

                timing       = m.group(1).upper()   # BEFORE / AFTER
                profile      = m.group(2).strip()
                storage_type = m.group(3).upper()   # HDD / SSD
                run_index    = int(m.group(4))

                current_key  = (profile, storage_type, run_index, timing)
                current_data = {}
                continue

            # Parse data rows if inside a section
            if current_key:
                d = DATA_ROW_RE.match(line)
                if d:
                    ost_id  = int(d.group(1))
                    free_gib = float(d.group(3))
                    node_id  = int(d.group(4))

                    # Filter to active nodes unless --all-nodes
                    if active_node_ids is None or node_id in active_node_ids:
                        current_data[ost_id] = free_gib

        # Save last section
        if current_key and current_data:
            records[current_key] = current_data

    return records


# ---------------------------------------------------------------------------
# Delta calculation
# ---------------------------------------------------------------------------

def compute_deltas(records):
    """
    For each (profile, storage_type, run_index), compute per-OST delta:
        delta_gib = BEFORE_free - AFTER_free  (positive = data was written)

    Returns list of dicts:
        [{profile, storage_type, run_index, ost_id, delta_gib}, ...]
    """
    # Group keys by (profile, storage, run)
    runs = defaultdict(dict)
    for (profile, storage, run, timing), ost_data in records.items():
        runs[(profile, storage, run)][timing] = ost_data

    rows = []
    for (profile, storage, run), timings in runs.items():
        if "BEFORE" not in timings or "AFTER" not in timings:
            print(f"  WARNING: Missing BEFORE or AFTER for {profile} [{storage}] run{run} — skipping")
            continue

        before = timings["BEFORE"]
        after  = timings["AFTER"]

        all_osts = set(before.keys()) | set(after.keys())
        for ost_id in all_osts:
            b = before.get(ost_id, 0.0)
            a = after.get(ost_id, 0.0)
            delta = b - a   # positive = space was consumed = data written
            rows.append({
                "profile":      profile,
                "storage_type": storage,
                "run_index":    run,
                "ost_id":       ost_id,
                "delta_gib":    max(delta, 0.0),  # clamp negatives (space freed) to 0
            })

    return rows


# ---------------------------------------------------------------------------
# Aggregation
# ---------------------------------------------------------------------------

def aggregate(rows):
    """
    Aggregate delta_gib across all runs of each (profile, storage_type).
    Returns a pivot DataFrame:
        index   = "profile [STORAGE]"
        columns = OST IDs (sorted)
        values  = mean delta_gib across runs
    """
    df = pd.DataFrame(rows)
    if df.empty:
        print("ERROR: No valid BEFORE/AFTER pairs found in log.")
        sys.exit(1)

    # Create combined label for y-axis
    df["label"] = df["profile"] + " [" + df["storage_type"] + "]"

    # Mean across runs
    agg = (
        df.groupby(["label", "ost_id"])["delta_gib"]
        .sum()
        .reset_index()
    )

    pivot = agg.pivot(index="label", columns="ost_id", values="delta_gib").fillna(0.0)
    pivot.columns = [f"OST{c}" for c in sorted(pivot.columns)]
    pivot = pivot.reindex(sorted(pivot.columns), axis=1)

    return pivot


# ---------------------------------------------------------------------------
# Heatmap generation
# ---------------------------------------------------------------------------

def generate_heatmap(pivot, output_path, active_only):
    """Render and save the OST heatmap."""

    if active_only:
        # Drop OST columns where every profile wrote 0 GiB
        pivot = pivot.loc[:, (pivot > 0).any(axis=0)]

    if pivot.empty:
        print("ERROR: Pivot table is empty after filtering — nothing to plot.")
        sys.exit(1)

    n_profiles = len(pivot)
    n_osts     = len(pivot.columns)

    # Dynamic figure size
    fig_w = max(14, n_osts * 0.9)
    fig_h = max(6,  n_profiles * 0.55 + 3)

    fig, ax = plt.subplots(figsize=(fig_w, fig_h))
    fig.patch.set_facecolor("#0f1117")
    ax.set_facecolor("#0f1117")

    # Color palette: dark background, vivid write intensity
    cmap = sns.color_palette("rocket", as_cmap=True)

    sns.heatmap(
        pivot,
        ax=ax,
        cmap=cmap,
        linewidths=0.4,
        linecolor="#1e2130",
        annot=True,
        fmt=".2f",
        annot_kws={"size": 7, "color": "white"},
        cbar_kws={"label": "Mean GiB Written", "shrink": 0.6},
    )

    # Style colorbar
    cbar = ax.collections[0].colorbar
    cbar.ax.yaxis.label.set_color("white")
    cbar.ax.tick_params(colors="white")
    cbar.outline.set_edgecolor("#444")

    # Titles and labels
    ax.set_title(
        "OST Write Distribution Heatmap\n(Mean GiB written per OST per workload — aggregated across runs)",
        color="white",
        fontsize=13,
        fontweight="bold",
        pad=16,
    )
    ax.set_xlabel("OST Target", color="#aaaaaa", fontsize=10, labelpad=8)
    ax.set_ylabel("Workload Profile", color="#aaaaaa", fontsize=10, labelpad=8)

    ax.tick_params(axis="x", colors="#cccccc", labelsize=8, rotation=45)
    ax.tick_params(axis="y", colors="#cccccc", labelsize=8, rotation=0)

    for spine in ax.spines.values():
        spine.set_edgecolor("#333")

    plt.tight_layout()

    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    plt.savefig(output_path, dpi=150, bbox_inches="tight", facecolor=fig.get_facecolor())
    plt.close()
    print(f"  Heatmap saved: {output_path}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    args = parse_args()

    active_node_ids = None if args.all_nodes else ACTIVE_NODE_IDS

    print(f"Parsing log: {args.log}")
    records = parse_log(args.log, active_node_ids)
    print(f"  Found {len(records)} BEFORE/AFTER sections")

    print("Computing per-OST write deltas...")
    rows = compute_deltas(records)
    print(f"  {len(rows)} (profile, storage, run, OST) data points")

    print("Aggregating across runs...")
    pivot = aggregate(rows)
    print(f"  Pivot: {len(pivot)} profiles × {len(pivot.columns)} OSTs")
    print(pivot.to_string())

    print("Generating heatmap...")
    generate_heatmap(pivot, args.output, args.active_only)

    print("\nDone.")


if __name__ == "__main__":
    main()